'use client';

import React from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

const chartData = [
  { day: 'Mon', socialPost: 8, adCopy: 3, emailSubject: 5, tagline: 2, blogIntro: 1 },
  { day: 'Tue', socialPost: 12, adCopy: 6, emailSubject: 4, tagline: 3, blogIntro: 2 },
  { day: 'Wed', socialPost: 5, adCopy: 2, emailSubject: 7, tagline: 1, blogIntro: 0 },
  { day: 'Thu', socialPost: 15, adCopy: 8, emailSubject: 6, tagline: 4, blogIntro: 3 },
  { day: 'Fri', socialPost: 9, adCopy: 5, emailSubject: 3, tagline: 2, blogIntro: 1 },
  { day: 'Sat', socialPost: 4, adCopy: 1, emailSubject: 2, tagline: 1, blogIntro: 0 },
  { day: 'Sun', socialPost: 6, adCopy: 3, emailSubject: 4, tagline: 2, blogIntro: 1 },
];

const COLORS = {
  socialPost: '#ededed',
  adCopy: '#a3a3a3',
  emailSubject: '#737373',
  tagline: '#525252',
  blogIntro: '#3a3a3a',
};

const CustomTooltip = ({ active, payload, label }: { active?: boolean; payload?: { name: string; value: number; color: string }[]; label?: string }) => {
  if (active && payload && payload.length) {
    return (
      <div className="rounded-[10px] p-3 min-w-[160px]" style={{ background: '#0d0d0d', border: '1px solid #1f1f1f' }}>
        <p className="text-[12px] font-semibold mb-2" style={{ color: '#ededed' }}>{label}</p>
        {payload.map((entry) => (
          <div key={`tooltip-${entry.name}`} className="flex items-center justify-between gap-4 text-[11px] mb-1">
            <span className="flex items-center gap-1.5 capitalize" style={{ color: '#8a8a8a' }}>
              <span className="w-2 h-2 rounded-full inline-block" style={{ backgroundColor: entry.color }} />
              {entry.name.replace(/([A-Z])/g, ' $1').trim()}
            </span>
            <span className="font-semibold font-tabular" style={{ color: '#ededed' }}>{entry.value}</span>
          </div>
        ))}
        <div className="mt-2 pt-2 flex justify-between text-[11px]" style={{ borderTop: '1px solid #1f1f1f' }}>
          <span style={{ color: '#8a8a8a' }}>Total</span>
          <span className="font-bold font-tabular" style={{ color: '#ededed' }}>
            {payload.reduce((s, e) => s + e.value, 0)}
          </span>
        </div>
      </div>
    );
  }
  return null;
};

export default function DashboardChart() {
  return (
    <div className="rounded-[11px] p-6" style={{ background: '#0d0d0d', border: '1px solid #1f1f1f' }}>
      <div className="flex items-start justify-between mb-6">
        <div>
          <h4 className="text-[11.5px] font-semibold uppercase tracking-[0.4px] mb-[4px]" style={{ color: '#8a8a8a' }}>Daily Impressions · 14d</h4>
          <h2 className="text-[16px] font-bold tracking-[-0.3px]" style={{ color: '#ededed' }}>Content Generated by Type</h2>
          <p className="text-[12px] mt-[2px]" style={{ color: '#8a8a8a' }}>Last 7 days · stacked by content type</p>
        </div>
        <div className="flex flex-wrap gap-3">
          {Object.entries(COLORS).map(([key, color]) => (
            <div key={`legend-${key}`} className="flex items-center gap-1.5">
              <span className="w-2.5 h-2.5 rounded-sm inline-block" style={{ backgroundColor: color }} />
              <span className="text-[11px] capitalize" style={{ color: '#8a8a8a' }}>{key.replace(/([A-Z])/g, ' $1').trim()}</span>
            </div>
          ))}
        </div>
      </div>
      <ResponsiveContainer width="100%" height={240}>
        <BarChart data={chartData} barSize={28} barCategoryGap="30%">
          <CartesianGrid strokeDasharray="3 3" stroke="#1f1f1f" vertical={false} />
          <XAxis
            dataKey="day"
            axisLine={false}
            tickLine={false}
            tick={{ fontSize: 11, fill: '#8a8a8a' }}
          />
          <YAxis
            axisLine={false}
            tickLine={false}
            tick={{ fontSize: 11, fill: '#8a8a8a' }}
          />
          <Tooltip content={<CustomTooltip />} cursor={{ fill: '#1f1f1f', radius: 6 }} />
          <Bar dataKey="socialPost" stackId="a" fill={COLORS.socialPost} radius={[0, 0, 0, 0]} />
          <Bar dataKey="adCopy" stackId="a" fill={COLORS.adCopy} />
          <Bar dataKey="emailSubject" stackId="a" fill={COLORS.emailSubject} />
          <Bar dataKey="tagline" stackId="a" fill={COLORS.tagline} />
          <Bar dataKey="blogIntro" stackId="a" fill={COLORS.blogIntro} radius={[4, 4, 0, 0]} />
        </BarChart>
      </ResponsiveContainer>
    </div>
  );
}