'use client';

import React from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,  } from 'recharts';

// Backend integration point: fetch /api/content/stats?range=7d
const chartData = [
  { day: 'Mon', socialPost: 8, adCopy: 3, emailSubject: 5, tagline: 2, blogIntro: 1 },
  { day: 'Tue', socialPost: 12, adCopy: 6, emailSubject: 4, tagline: 3, blogIntro: 2 },
  { day: 'Wed', socialPost: 5, adCopy: 2, emailSubject: 7, tagline: 1, blogIntro: 0 },
  { day: 'Thu', socialPost: 15, adCopy: 8, emailSubject: 6, tagline: 4, blogIntro: 3 },
  { day: 'Fri', socialPost: 9, adCopy: 5, emailSubject: 3, tagline: 2, blogIntro: 1 },
  { day: 'Sat', socialPost: 4, adCopy: 1, emailSubject: 2, tagline: 1, blogIntro: 0 },
  { day: 'Sun', socialPost: 6, adCopy: 3, emailSubject: 4, tagline: 2, blogIntro: 1 },
];

const COLORS = {
  socialPost: 'var(--primary)',
  adCopy: 'var(--accent)',
  emailSubject: '#0ea5e9',
  tagline: '#10b981',
  blogIntro: '#f43f5e',
};

const CustomTooltip = ({ active, payload, label }: { active?: boolean; payload?: { name: string; value: number; color: string }[]; label?: string }) => {
  if (active && payload && payload.length) {
    return (
      <div className="bg-card border border-border rounded-xl shadow-dropdown p-3 min-w-[160px]">
        <p className="text-xs font-semibold text-foreground mb-2">{label}</p>
        {payload.map((entry) => (
          <div key={`tooltip-${entry.name}`} className="flex items-center justify-between gap-4 text-xs mb-1">
            <span className="flex items-center gap-1.5 text-muted-foreground capitalize">
              <span className="w-2 h-2 rounded-full inline-block" style={{ backgroundColor: entry.color }} />
              {entry.name.replace(/([A-Z])/g, ' $1').trim()}
            </span>
            <span className="font-semibold font-tabular text-foreground">{entry.value}</span>
          </div>
        ))}
        <div className="border-t border-border mt-2 pt-2 flex justify-between text-xs">
          <span className="text-muted-foreground">Total</span>
          <span className="font-bold font-tabular text-foreground">
            {payload.reduce((s, e) => s + e.value, 0)}
          </span>
        </div>
      </div>
    );
  }
  return null;
};

export default function DashboardChart() {
  return (
    <div className="card-base p-6">
      <div className="flex items-start justify-between mb-6">
        <div>
          <h2 className="text-base font-semibold text-foreground">Content Generated by Type</h2>
          <p className="text-xs text-muted-foreground mt-0.5">Last 7 days · stacked by content type</p>
        </div>
        <div className="flex flex-wrap gap-3">
          {Object.entries(COLORS).map(([key, color]) => (
            <div key={`legend-${key}`} className="flex items-center gap-1.5">
              <span className="w-2.5 h-2.5 rounded-sm inline-block" style={{ backgroundColor: color }} />
              <span className="text-xs text-muted-foreground capitalize">{key.replace(/([A-Z])/g, ' $1').trim()}</span>
            </div>
          ))}
        </div>
      </div>
      <ResponsiveContainer width="100%" height={240}>
        <BarChart data={chartData} barSize={28} barCategoryGap="30%">
          <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" vertical={false} />
          <XAxis
            dataKey="day"
            axisLine={false}
            tickLine={false}
            tick={{ fontSize: 12, fill: 'var(--muted-foreground)' }}
          />
          <YAxis
            axisLine={false}
            tickLine={false}
            tick={{ fontSize: 12, fill: 'var(--muted-foreground)' }}
          />
          <Tooltip content={<CustomTooltip />} cursor={{ fill: 'var(--muted)', radius: 8 }} />
          <Bar dataKey="socialPost" stackId="a" fill={COLORS.socialPost} radius={[0, 0, 0, 0]} />
          <Bar dataKey="adCopy" stackId="a" fill={COLORS.adCopy} />
          <Bar dataKey="emailSubject" stackId="a" fill={COLORS.emailSubject} />
          <Bar dataKey="tagline" stackId="a" fill={COLORS.tagline} />
          <Bar dataKey="blogIntro" stackId="a" fill={COLORS.blogIntro} radius={[4, 4, 0, 0]} />
        </BarChart>
      </ResponsiveContainer>
    </div>
  );
}